port: "8080"

users_service:
  host: "purchases"
  port: "8080"
  confirm_urn: "confirm"
  synchro_urn: ""
  scheme: "http://"

db_pg:
  host: "db-shops"
  port: "5432"
  username: "postgres"
  password: "1"
  dbname: "postgres"
  sslmode: "disable"

rabbitmq:
  host: "rabbit"
  port: "5672"
  username: "rabbit"
  password: "1"