version: '3'

services:
  purchases:
    #build: ./purchases
    image: ddzzan/purchases
    command: ./main
    container_name: purchases
    environment:
      - DB_PASSWORD=1
      - JWT_SECRET_KEY=H+0MpgoFbwAcmXISyCS9vr0x(WAkc@
      - PASS_GEN_SALT=NZIl!#Qv$an(4akm*wP9=jo&2!55UR)
      - USERS_TRANSPORT_KEY=Zr8(#K95vi8kdUlniC7VaWSsYxUFNhBy
    expose:
    - 8080
    depends_on: 
    - db-purchases
    - rabbit
    networks:
    - l1
    - n1
    - rabbitmq
    - proxy

  db-purchases:
    image: postgres
    container_name: db-purchases
    volumes: 
    - db-data-purchases:/var/lib/postgresql/data
    - ./purchases/scheme/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DATABASE: postgres
    networks:
    - l1

  shops:
    #build: ./shops
    image: ddzzan/shops
    command: ./main
    container_name: shops
    environment:
      - USERS_TRANSPORT_KEY=Zr8(#K95vi8kdUlniC7VaWSsYxUFNhBy
      - JWT_SECRET_KEY=)0OHGFz1Mo9a@rs)%IYNxV3kBf3txnWm
      - DB_PASSWORD=1
    expose: 
    - 8080
    depends_on:
    - db-shops
    - rabbit
    - purchases
    networks:
    - l2
    - n1
    - rabbitmq
    - proxy

  db-shops:
    image: postgres
    container_name: db-shops
    volumes: 
    - db-data-shops:/var/lib/postgresql/data
    - ./shops/schema/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DATABASE: postgres
    networks:
    - l2
  
  rabbit:
    hostname: 'rabbit'
    image: rabbitmq:3.6-management-alpine
    container_name: rabbit
    #healthcheck:
      #test: ["CMD", "curl", "-f", "http://localhost:5672"]
      #interval: 30s
      #timeout: 30s
      #retries: 3
    #ports:
    #  - '5672:5672'
    #  - '15672:15672'
    volumes:
      - 'rabbit-data:/var/lib/rabbitmq/'
    networks:
      - rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=1

  fabric:
    #build: ./fabric
    image: ddzzan/fabric
    container_name: fabric
    environment: 
    - DB_PASSWORD=1
    networks:
    - rabbitmq
    - l3
    depends_on:
    - rabbit
    - db-fabric

  db-fabric:
    image: postgres
    volumes: 
    - db-data-fabric:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DATABASE: postgres
    networks:
    - l3

  nginx:
    image: nginx
    container_name: nginx
    volumes:
    - ./reverse_proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 8081:8081
    networks: 
    - proxy
    depends_on: 
    - shops
    - purchases
    links: 
    - shops
    - purchases

networks: 
  l1:
    driver: bridge
  l2:
    driver: bridge
  l3:
    driver: bridge
  n1:
    driver: bridge
  rabbitmq:
    driver: bridge
  proxy:
    driver: bridge

volumes:
  db-data-purchases:
  db-data-shops:
  rabbit-data:
  db-data-fabric: